window.tyrano_lang = {
    word: {
        go_title: "타이틀 화면으로 돌아갑니다. 괜찮을까요？",
        exit_game: "윈도우를 닫고 종료합니다. 괜찮을까요?",
        not_saved: "아직 저장 데이터가 없습니다.",
        tag: "태그",
        not_exists: "(은)는 존재하지 않습니다.",
        error: "에러가 발생했습니다. 스크립트를 확인해주세요.",
        label: "라벨",
        label_double: "(은)는 동일 시나리오 내에 중복되고 있습니다.",
        error_occurred: "에러가 발생했습니다.",
        save_file_violation_1: "저장 데이터 이동을 감지했습니다. 신뢰할 수 있는 저장 데이터가 아닌 경우 절대로 로드하지 마십시오.",
        save_file_violation_2: "저장 데이터를 로드하고 게임을 시작하시겠습니까?",
        save_file_violation_3: "기동을 중지했습니다. 저장 데이터를 삭제하고 다시 시작하십시오.",
        double_start: "이미 게임이 시작되었습니다. 2중으로 기동은 할 수 없습니다.",
        reload: "리로드",
    },

    novel: {
        file_menu_button_save: "menu_button_save.gif",
        file_menu_button_load: "menu_button_load.gif",
        file_menu_button_message_close: "menu_message_close.gif",
        file_menu_button_skip: "menu_button_skip.gif",
        file_menu_button_title: "menu_button_title.gif",
        file_menu_button_close: "menu_button_close.png",
        file_menu_bg: "menu_bg.jpg",
        file_save_bg: "menu_save_bg.jpg",
        file_load_bg: "menu_load_bg.jpg",
        file_button_menu: "button_menu.png",
        error_occurred: "error occurred",
    },
};
